qudao/extra_apps/xadmin/demo_app/demo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()

from django.contrib import admin

urlpatterns = [
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(xadmin.site.urls))
]

qudao/oms_web/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from oms.views import *
from dbmanager.views import *
from users.views import *
from version.views import *
import xadmin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', Login.as_view(), name='Login'),
    url(r'^index/$', index, name='index'),
    url(r'^remote_exec/$', remote_exec, name='remote_exec'),
#    url(r'^HostManage/$',  HostManage,  name='HostManage'),
    url(r'^addip/$',       Addip,       name='Addip'),
    url(r'^cmdrun/$',      cmdrun.as_view(),      name='cmdrun'),
    url(r'^dayend/$',      dayend,      name='dayend'),
    url(r'^dbmanage/$',    dbmanage,    name='dbmanage'),
    url(r'^pg2manage/$',    pg2manage,    name='pg2manage'),
    url(r'^autodeploy/$',  Autodeploy.as_view(),  name='autodeploy'),
    # url(r'^add/$',         add,         name='add'),
    url(r'^dbm/', include('dbmanager.urls',namespace="dbm")),
    url(r'^version/',include('version.urls',namespace="version")),
]

qudao/version/urls.py
# coding:utf-8
from django.conf.urls import url
from django.contrib import admin
from version.views import *
from django.conf.urls import (
        handler400,handler403,handler404,handler500
)

# handler400 = 'webadmin.handle_views.bad_request'
# handler403 = 'webadmin.views.permission_denied'
handler404 = 'version.views.page_not_found'
# handler500 = 'webadmin.handle_views.server_error'

urlpatterns = [
        # url(r'^(\w+)', ChDb.as_view(), name='ChDb'),
        # url(r'^ChMap/$', ChDb.as_view(), name='group_obj'),
        # url(r'^ChAgent/$', ChDb.as_view(), name='group_obj'),
        url(r'^(\w+)/$', ChDb.as_view(), name='group_obj'),
        # url(r'^DayEnd/$', ChDb.as_view(), name='group_obj'),
]

qudao/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

qudao/templates/autodeploy.html
{% extends 'base.html' %}
{% block title %}日终任务管理{% endblock %}
{% block link_js %}
    <style type="text/css">
        *{
            font-family: 微软雅黑;
        }
    </style>

{% endblock %}
{% block right %}
    <div class="king-layout6-content">
        <div class="col-md-10 col-md-offset-1">

            <h3 class="page-header text-center text-info">应用部署</h3>

            <div class=" alert alert-danger alert-dismissible" id="message_dg" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span
                        aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <p id="message_d">请先修改部署主机的配置文件文件（/home/ansible/app.conf）
                <p>
            </div>
            <div class="panel panel-success ">
                <div class="panel-body">
                    <a class="btn btn-info" href="?yybs=ljbs" role="button">联机部署</a>
                    <a class="btn btn-info" href="?yybs=sjdl" role="button">数据代理</a>
                    <a class="btn btn-info" href="?yybs=lsbs" role="button">流水部署</a>
                </div>
            </div>
            <div>
                <label class="col-md-3 control-label"><h4 class="text-info"><span>部署过程 :</span></h4></label>
                <div class="stype=overflow:scroll">
                    <textarea class="form-control" rows="10">{{ autodeploy_yybs }}</textarea>
                </div>
            </div>


            <h3 class="page-header text-center text-success">系统部署</h3>

            <div class=" alert alert-danger alert-dismissible"  role="alert">
                <button type="button" class="close" data-dismiss="alert"><span
                        aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <p >请先修改部署主机的配置文件文件（/home/ansible/system.conf）
                <p>
            </div>
            <div class="panel panel-success ">
                <div class="panel-body">
                    <a class="btn btn-success" href="?xtbs=ps" role="button">部署Postgres</a>
                    <a class="btn btn-success" href="?xtbs=rs" role="button">部署Redis</a>
                    <a class="btn btn-success" href="?xtbs=ml" role="button">部署Mysql</a>
                </div>
            </div>
            <div>
                <label class="col-md-3 control-label"><h4 class="text-success"><span>部署过程 :</span></h4></label>
                <div class="stype=overflow:scroll">
                    <textarea class="form-control" rows="10">{{ autodeploy_xtbs }}</textarea>
                </div>
            </div>


        </div>

    </div>

{% endblock %}

qudao/templates/base_version.html
{% extends 'base.html' %}
{% block my_css %}
    .add-pub-btn {
    width: 90px;
    height: 32px;
    display: inline-block;
    text-align: center;
    color: #fff;
    padding-right: 20px;
    position: relative;

    }
    .my-inp-btn {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0px;
    right: 0px;
    left: 0px;
    bottom: 0px;
    opacity: 0;

    }
{% endblock %}
{% block title %}{% endblock %}
{% block right %}

    <div class="king-layout6-content">
        <div class="col-md-10 col-md-offset-1">
            <h3 class="page-header text-center text-info">{% block title_rollback %}{% endblock %}</h3>
            <div class="form-group has-success">
                <form class="form-inline" role="form" id="rollback_form">
                    {% csrf_token %}
                    <label class="control-label">版本号：</label>
                    <div class="form-group">
                        <select class="form-control" name='roll_choice_vers'>
                            {% for version_num in version_list %}
                                <option value="{{ version_num }}">{{ version_num }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <label class="col-md-offset-1 control-label">主机范围：</label>
                    <div class="form-group">
                        <div class="col-md-6 input-group">
                            <input class="col-md-2 form-control error_input" type="text" name="start_host"
                                   placeholder="0-10">
                            <div class="input-group-addon">——</div>
                            <input class="col-md-1 form-control error_input" type="text" name="end_host"
                                   placeholder="0-10">
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="button" class="btn btn-primary " id="rollback_btn">回滚</button>
                    </div>

                </form>

                <blockquote></blockquote>
                {#            <input class="form-control" type="text" placeholder="Readonly input here…" readonly>#}
                <div class=" alert alert-info" id="message_dg" role="alert">
                    <p id="message_d">主机范围：{{ host_range }}</p>
                </div>

                <div>
                    <div>
                        <label class="col-md-3 control-label"><h4 class="text-info"><span>回滚过程 :</span></h4></label>
                    </div>
                    <div class="stype=overflow:scroll">
                        <textarea class="form-control" rows="8" id="rollback_text">{{ autodeploy_yybs }}</textarea>
                    </div>
                </div>

                <div><h3 class="page-header text-center text-info">{% block title_upgrade %}{% endblock %}</h3></div>
                <form class="form-horizontal" role="form"
                      id="ifram_update_form"
                        {#              action="{% url 'version:group_obj' 'chmap' %}"#}
                      action="{{ request.path }}"
                      method="POST"
                      enctype="multipart/form-data"
                      target="ifr">
                    {% csrf_token %}

                    <div class="form-group">
                        <button class="btn btn-primary add-pub-btn">上传升级包
                            <input class="my-inp-btn" type="file" name="v_file_obj" id="inputfile">
                        </button>
                        <span id="chioce_file_name">未选择任何文件</span>
                    </div>
                    <div class="col-md-offset-1 form-group">
                        <label class="control-label">主机范围：</label>
                        <div class="col-md-6 input-group">
                            <input class="form-control error_input" type="text" name="start_host" placeholder="0-10">
                            <div class="input-group-addon">——</div>
                            <input class="form-control error_input" type="text" name="end_host" placeholder="0-10">
                        </div>
                    </div>

             <div class="col-md-6 form-group">
                 <label class="col-md-4 control-label">打包内容</label>
             </div>
                    <div>
               <div style="margin-top: 15px;">
                    <div class="col-md-12 form-group">
                        <div>
                            <textarea class="col-md-12 form-control stype=overflow:scroll" rows="4" name="packge_content" id="file_text">
                            </textarea>
                        </div>
                    </div>
                </div>
</div>
                    <div class="col-md-offset-1 form-group">
                        <button type="button" class="btn btn-primary " id="update_btn">升级</button>
                    </div>
                </form>

                <!--ifram tag-->
                <iframe id="ifr-load" name="ifr" style="display: none"></iframe>
                <div>
                    <div>
                        <label class="col-md-3 control-label">
                            <h4 class="text-info"><span>升级过程 :</span></h4>
                        </label>
                    </div>
                    <div class="stype=overflow:scroll">
                        <textarea class="form-control" rows="8"
                                  id="update_text">{{ autodeploy_yybs }}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block my_script %}
    <script>
        $(".error_input").on('foupdate_textcus', function () {
            $(this).css('border-color', '');

        });
        $("button#rollback_btn").on('click', function () {
            //<input class="col-md-1 form-control" name="method" type="text" value="version_rollback"/>
            {#            var group_name = '{{ group_name }}'#}
            $.post(
                "{{ request.path }}",

                //获取到 form 表单的所有数据，并进行序列化
                $("form#rollback_form").serialize(),

                // 回调函数
                function (callback) {

                    // 从后台返回的数据进行序列化，得到 jQuiery 对象
                    var data = JSON.parse(callback);
                    if (data.status) {
                        $("textarea#rollback_text").text(data.data);
                    } else {
                        $("#rollback_form input[type='text']").css('border-color', 'rgb(222,97,94)');
                        $("textarea#rollback_text").text(data.error);
                    }
                    ;
                }); // end ajax
        }); // end click


        //  版本升级
        // ifram + form "伪" Ajax 提交表单和文件
        // 1. 先检查上传文件

        $("input#inputfile").on('change', function () {
            var inp_file = $("input#inputfile").val();
            if (inp_file) {
                var flag = true;
                var pos = inp_file.lastIndexOf("\\");
                var jquery_file_name = inp_file.substring(pos + 1);
                $("span#chioce_file_name").text(" 上传的文件：" + jquery_file_name);
                if (!inp_file.match(/.tar.gz/i)) {
                    $("input#inputfile").val("");
                    alert("文件格式错误,仅支持 .tar.gz 格式");
                    flag = false;
                    return flag;
                }
                ;
                return flag
            }
            ;
        });


        // 2. 检查完毕开始提交表单数据和文件
        $("#update_btn").on('click', function () {
            var inp_file = $("input#inputfile").val();

            var update_items     = $("textarea#file_text").val();

            //用于把变量的值为：null、空字符串和任意数量的空格都替换为空字符串，之后判断其长度
            //这样就可以判断变量的值是否有输入。
            var update_items_num = update_items.replace(/(^\s*)|(\s*$)/g, "").length

            if (!inp_file) {
                alert("请选择上传的升级包");  // 预防不传升级包直接点提交
                return false;
            }
            ;

            // 检查是否填写了需要升级的目录名或文件名的相对路径
            if (update_items_num == 0) {
                alert("请输入打包后需要升级的内容(目录文件的相对路径)");
                $("textarea#file_text").css('border-color', 'rgb(222,97,94)');
                return false;
            }
            ;
            var s_host_value = $("#ifram_update_form input[name='start_host']").val();
            var e_host_value = $("#ifram_update_form input[name='end_host']").val();

            if (!s_host_value) {
                alert("请输入起始主机范围");
                $("#ifram_update_form input[type='text']").css('border-color', 'rgb(222,97,94)');
                return false;
            }
            ;
            if (!e_host_value) {
                alert("请输入结束主机范围");
                $("#ifram_update_form input[type='text']").css('border-color', 'rgb(222,97,94)');
                return false;
            }
            ;

            $("#ifram_update_form").submit(); // 提交
        });

        // 3. 接收后台反回的数据
        $("iframe#ifr-load").on('load', function () {
            // 返回的数据会在 ifram 中，从ifram中取数据
            var result_data = $('iframe#ifr-load').contents().find('body').html();
            var result_obj = JSON.parse(result_data);
            $("textarea#update_text").val("返回状态：" + result_obj.status + '\n' +
                "返回数据内容：" + result_obj.data + '\n' +
                "返回的错误信息：" + result_obj.error);
        });

        // Ajax 提交表单
        {#        $("button#update_btn").on('click',function () {#}
        {#            $.post(#}
        {#                    "{% url 'version:group_obj' %}",#}
        {#                    $("form#update_form").serialize(),#}
        {#                    function (callback) {#}
        {#                        var data = JSON.parse(callback);#}
        {#                        if (data.status) {#}
        {#                            $("textarea#update_text").text(data.data);#}
        {#                        } else {#}
        {#                            $("#update_form input[type='text']").css('border-color', 'rgb(222,97,94)');#}
        {#                            $("textarea#update_text").text(data.error);#}
        {#                        }#}
        {#                    });#}
        {#        })#}
    </script>
{% endblock %}

qudao/templates/chagentversion.html
{% extends 'base_version.html' %}
{% block title %}数据代理升级{% endblock %}
{% block title_rollback %}数据代理版本回滚{% endblock %}
{% block title_upgrade %}数据代理版本升级{% endblock %}

qudao/templates/chmapversion.html
{% extends 'base_version.html' %}
{% block title %}联机代理升级{% endblock %}
{% block title_rollback %}联机代理版本回滚{% endblock %}
{% block title_upgrade %}联机代理版本升级{% endblock %}

qudao/templates/dayend.html
{% extends 'base.html' %}
{% block title %}日终任务管理{% endblock %}
{% block right %}
<script type="text/javascript">
  $(document).ready(function(){
      if($("#message_p").html()){
        $("#message_wg").show();
      }
  });
</script>

<div class="king-layout6-content">
    <h3 class="page-header text-center text-success">日终任务管理库</h3>
  <div class="col-md-11" style="margin:10px 30px " >
    <div class="panel panel-primary">
      <div class="panel-body">
        <form  class="form-inline"  method="post"  enctype="multipart/form-data"role="form">
          {% csrf_token %}

             <div class="form-group" >
                <label class="control-label">ID查询:</label>
                <input  type="text"  size="35" class="form-control"  name="sqlOrder" >
            </div>

             <div class="form-group" >
                <label class="control-label">日期查询:</label>
                <input  type="text"  size="35" class="form-control"  name="sqlOrder" >
            </div>
          <button type="submit" class="col-md-offset-1 btn btn-primary " name="" id="execute" value="execute">执行</button>
          <button type="submit" class=" btn btn-danger " name="" id="cancel" value="cancel">取消</button>
        </form>
      </div>
    </div>
  </div>

   <div class="col-md-10 alert alert-danger alert-dismissible" id="message_wg" hidden="hidden" role="alert" style="margin:0 45px" >
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <p id="message_p" >{{ pg2manage_txt }}{{ msg }}<p>
   </div>


  <div class="col-md-11" style="margin:10px 30px ">
    <div class="panel panel-primary">
      <div class="panel-heading">输出数据：</div>
      <div class="panel-body" style="position:relative;height:350px;overflow-x:auto;overflow-y:auto">
       <!-- Table -->
<!--        <table class="table">
        <th>产品</th><th>价格 </th>
        <tr>
          <td>产品 A</td>
          <td>200</td>
        </tr>
      </table> -->

	{% if col_names %}
	<table class="table table-bordered">

        {% for row in dbvalue_txt %}
        <tr>
        <td>{{ row.0  }}</td>
        <td>{{ row.1  }}</td>
        <td>{{ row.2  }}</td>
        <td>{{ row.3  }}</td>
        <td>{{ row.4  }}</td>
        <td>{{ row.5  }}</td>
        <td>{{ row.6  }}</td>
        <td>{{ row.7  }}</td>
        <td>{{ row.8  }}</td>
        <td>{{ row.9  }}</td>
        <td>{{ row.10 }}</td>
        <td>{{ row.11  }}</td>
        <td>{{ row.12  }}</td>
        <td>{{ row.13  }}</td>
        <td>{{ row.14  }}</td>
        <td>{{ row.15  }}</td>

        </tr>
        {% endfor %}
        </table>
		    {% else %}
              <p class="text-success">{{dbvalue_txt}}</p>
        {% endif %}

    </div>
    </div>
  </div>
</div>

{% endblock %}

qudao/templates/dbmanage.html
{% extends 'base.html' %}
{% block title %}MySQLdb数据库管理{% endblock %}
{% block right %}
<script type="text/javascript">
  $(document).ready(function(){
      if($("#message_p").html()){
        $("#message_wg").show();
      }
  });
</script>

<div class="king-layout6-content">
     <h3 class="page-header text-center text-success">Mycat 日常维护</h3>
  <div class="col-md-11" style="margin:10px 30px " >
    <div class="panel panel-primary">
      <div class="panel-body">
        <form  class="form-inline"  method="post"  enctype="multipart/form-data"role="form">
          {% csrf_token %}
          <label class="control-label">SQL语句:</label>
             <div class="form-group" >
              <input  type="text"  size="90" class="form-control"  name="sqlOrder" >
            </div>      
          <button type="submit" class="col-md-offset-1 btn btn-primary " name="" id="execute" value="execute">执行</button>
          <button type="submit" class=" btn btn-danger " name="" id="cancel" value="cancel">取消</button>
        </form>
      </div>
    </div>
  </div>

  <div class="col-md-10 alert alert-danger alert-dismissible" id="message_wg" hidden="hidden" role="alert" style="margin:0 45px" >
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <p id="message_p" >{{ dbmanage_txt }}{{ msg }}<p>
    </div>

  
  <div class="col-md-11" style="margin:10px 30px ">
    <div class="panel panel-primary">
      <div class="panel-heading">输出数据：</div>
      <div class="panel-body" style="position:relative;height:350px;overflow-x:auto;overflow-y:auto">
       <!-- Table -->
<!--        <table class="table">
        <th>产品</th><th>价格 </th>
        <tr>
          <td>产品 A</td>
          <td>200</td>
        </tr>
      </table> -->
          {% if col_names %}
          <table class="table table-bordered">
              {% for col_nm in col_names %}
              <th>{{ col_nm }}</th>
              {% endfor %}
              {% for row in dbvalue_txt %}
              <tr>
                  <td>{{ row.0 }}</td>
                  <td>{{ row.1 }}</td>
                  <td>{{ row.2 }}</td>
                  <td>{{ row.3 }}</td>
                  <td>{{ row.4 }}</td>
                  <td>{{ row.5 }}</td>
                  <td>{{ row.6 }}</td>
                  <td>{{ row.7 }}</td>
                  <td>{{ row.8 }}</td>
                  <td>{{ row.9 }}</td>
                  <td>{{ row.10 }}</td>
                  <td>{{ row.11 }}</td>
                  <td>{{ row.12 }}</td>
                  <td>{{ row.13 }}</td>
                  <td>{{ row.14 }}</td>
                  <td>{{ row.15 }}</td>

              </tr>
              {% endfor %}
          </table>
          {% else %}
                <p class="text-success">{{dbvalue_txt}}</p>
          {% endif %}

    </div>
    </div>
  </div>
</div>

{% endblock %}

qudao/templates/tellerchdbversion.html
{% extends 'base_version.html' %}
{% block title %}尾箱数据处理升级{% endblock %}
{% block title_rollback %}尾箱数据处理版本回滚{% endblock %}
{% block title_upgrade %}尾箱数据处理版本升级{% endblock %}